name: Run deploy 

on:
  push:
    branches:
      - developer


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
           python-version: '3.8.0'
      - name: Install deps
        run: make ci-setup
      - name: AWS profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: awsadm
          region: sa-east-1
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run Tests
        run: make ci-test  
      - name: Right version of troposphere
        run: pip install troposphere==2.7.1
      - name: Right version of Zappa
        run: pip install zappa==0.52.0 
      - name: Run Deploy
        run: make ci-deploy stage=prod

