name: Run test on Feature Branch

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - name: Install deps
        run: make ci-setup
      - name: Run Tests
        run: make ci-test  


